### ISSUE TITLE
Request for improvements with returning currencySymbol also

### ISSUE THREAD

**Issue by FoxyGirl** [andreasbergqvist/simple-currency-format#24]
Many thanks for your amazing package for currency formatting

Is it possible to add a function which will return currencySymbol also, 
to not add additional currency-symbol-map package in a project?

Something like

```
  function getCurrencySymbol(
    currency: CurrencyCode,
  ) {
    return  currencySymbols[currency];
  }
```

**Comment by andreasbergqvist** [comment]
Thanks!
A new version 2.4.0 with this function is now published.
